// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2nxpDlTjWm-6B0ee3BLssgFq4exXw2C0',
    appId: '1:1050631832159:web:9a621e94774475ead411ea',
    messagingSenderId: '1050631832159',
    projectId: 'loginflutter-5a1de',
    authDomain: 'loginflutter-5a1de.firebaseapp.com',
    storageBucket: 'loginflutter-5a1de.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3KrIOGv11QpcQh59cfYdfpbSQSU8H0mo',
    appId: '1:1050631832159:android:e221755aca9e48bed411ea',
    messagingSenderId: '1050631832159',
    projectId: 'loginflutter-5a1de',
    storageBucket: 'loginflutter-5a1de.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWrQbwSACWI6-F4MNyn3FGssWCuZFNgEs',
    appId: '1:1050631832159:ios:ae10cbe43c7254ced411ea',
    messagingSenderId: '1050631832159',
    projectId: 'loginflutter-5a1de',
    storageBucket: 'loginflutter-5a1de.appspot.com',
    iosClientId: '1050631832159-md2uo86g5dmqa6f12hf8k9t3kl8c8rn1.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginflutterfirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWrQbwSACWI6-F4MNyn3FGssWCuZFNgEs',
    appId: '1:1050631832159:ios:ae10cbe43c7254ced411ea',
    messagingSenderId: '1050631832159',
    projectId: 'loginflutter-5a1de',
    storageBucket: 'loginflutter-5a1de.appspot.com',
    iosClientId: '1050631832159-md2uo86g5dmqa6f12hf8k9t3kl8c8rn1.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginflutterfirebase',
  );
}
